exclude:
  # Exclude files or packages matching their paths
  paths:
    - \.pb\.go$   # excludes all protobuf generated files
    - ^contracts  # exclude package `contracts`
    - fork.go     # exclude file `fork.go`