name: Go test coverage check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  go-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # Configure action by specifying input parameters individually (option 2).
          # If you are using config file you shouldn't use these parameters.
          profile: cover.out
          local-prefix: github.com/org/project
          threshold-file: 75
          threshold-package: 80
          threshold-total: 90