name: go test
defaults:
  run:
    shell: bash -leo pipefail {0}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  go-test-ci:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: "Install foundry"
        run: |
          curl -L https://foundry.paradigm.xyz | bash;
          source ~/.bashrc;
          foundryup
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Test with the Go CLI
        run: go test $(go list ./... | grep -v /contracts)