name: Golang CI
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  go-ci:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: "Install foundry"
        shell: bash
        run: |
          curl -L https://foundry.paradigm.xyz | bash;
          source ~/.bashrc;
          foundryup
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude-dir=contracts ./...'
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      # - name: Install dependencies
      #   run: go get .
      - name: Test with the Go CLI
        run: go test $(go list ./... | grep -v /contracts)